## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('ibolsr', ['internet', 'config-store', 'point-to-point', 'wifi', 'mobility', 'applications', 'csma'])
    module.includes = '.'
    module.source = [
        'model/ibolsr-header.cc',
        'model/ibolsr-state.cc',
        'model/ibolsr-routing-protocol.cc',
        'helper/ibolsr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ibolsr')
    module_test.source = [
        'test/bug780-test.cc',
        'test/hello-regression-test.cc',
        'test/ibolsr-header-test-suite.cc',
        'test/regression-test-suite.cc',
        'test/ibolsr-routing-protocol-test-suite.cc',
        'test/tc-regression-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ibolsr'
    headers.source = [
        'model/ibolsr-routing-protocol.h',
        'model/ibolsr-header.h',
        'model/ibolsr-state.h',
        'model/ibolsr-repositories.h',
        'helper/ibolsr-helper.h',
        ]


    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
