## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('lsr', ['internet', 'config-store', 'point-to-point', 'wifi', 'mobility', 'applications', 'csma'])
    module.includes = '.'
    module.source = [
        'model/lsr-header.cc',
        'model/lsr-state.cc',
        'model/lsr-routing-protocol.cc',
        'helper/lsr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('lsr')
    module_test.source = [
        'test/bug780-test.cc',
        'test/hello-regression-test.cc',
        'test/lsr-header-test-suite.cc',
        'test/regression-test-suite.cc',
        'test/lsr-routing-protocol-test-suite.cc',
        'test/tc-regression-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'lsr'
    headers.source = [
        'model/lsr-routing-protocol.h',
        'model/lsr-header.h',
        'model/lsr-state.h',
        'model/lsr-repositories.h',
        'helper/lsr-helper.h',
        ]


    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
